DELETE FROM D_DWH.ETL_FW.RUN_BOOK WHERE BATCH = 'D9318_GORWCA_D';

INSERT INTO D_DWH.ETL_FW.RUN_BOOK (BATCH, DONE_OBJECTS_PRE_COND, FREQ, BIZ_DATE, SCHED, RUN_DATE, TRIGGER_TIME, SLA) 
SELECT 'D9318_GORWCA_D', 'S2000_TSYSP_SS_D_BATCH, S7000_EXADATA_SS_D_BATCH,S8033_ODS_LKP_GOREWARDS_PRODUCTS_SS_D_BATCH', 'daily', NULL, OBJECT_CONSTRUCT('time', '8,00'), NULL, '8,00', NULL;