

----------------------------------------

--JOB_D9318_GORWCA_D_OPEN_BATCH
DELETE FROM D_DWH.ETL_FW.BATCH_JOB WHERE BATCH_NAME = 'D9318_GORWCA_D' and JOB_NAME = 'JOB_D9318_GORWCA_D_OPEN_BATCH';   

INSERT INTO D_DWH.ETL_FW.BATCH_JOB(JOB_NAME, SRC_SYS, BATCH_NAME, JOB_TYPE, PARAMETERS)
SELECT  'JOB_D9318_GORWCA_D_OPEN_BATCH' JOB_NAME, 
    NULL SRC_SYS,
    'D9318_GORWCA_D' BATCH_NAME,
    'BATCH_MAINTENANCE' JOB_TYPE,
    OBJECT_CONSTRUCT(
        'activity', 'open batch'
    ) PARAMETERS;

---------------------------------------
--JOB_PARTITION_KEY_BGORWCA_D
DELETE FROM D_DWH.ETL_FW.BATCH_JOB WHERE BATCH_NAME = 'D9318_GORWCA_D' and JOB_NAME = 'JOB_PARTITION_KEY_BGORWCA_D';    
INSERT INTO D_DWH.ETL_FW.BATCH_JOB(JOB_NAME, BATCH_NAME, JOB_TYPE, MODE, PARAMETERS, SRC_SYS)
SELECT 'JOB_PARTITION_KEY_BGORWCA_D', 'D9318_GORWCA_D', 'TRANSFORMATION', NULL, OBJECT_CONSTRUCT(
  'data_columns', 'LOW_DT, HIGH_DT',
  'key_columns', 'BATCH_NAME',
  'load_pattern', 'km_dsf_insert',
  'source', 'DB_CONSUMER_BANKING.WGORWCA.XV_PARTITION_KEY_BGORWCA_D',
  'target', 'DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY',
  'truncate_table_before_loading', true
), NULL;

--------------------------------------------

-- JOB_D9318_GORWCA_D_GO_NO_GO
DELETE FROM D_DWH.ETL_FW.BATCH_JOB WHERE BATCH_NAME = 'D9318_GORWCA_D' and JOB_NAME = 'JOB_D9318_GORWCA_D_GO_NO_GO';  

INSERT INTO D_DWH.ETL_FW.BATCH_JOB(JOB_NAME, SRC_SYS, BATCH_NAME, JOB_TYPE, PARAMETERS)
SELECT  'JOB_D9318_GORWCA_D_GO_NO_GO' JOB_NAME, 
    NULL SRC_SYS,
    'D9318_GORWCA_D' BATCH_NAME,
    'BATCH_MAINTENANCE' JOB_TYPE,
    OBJECT_CONSTRUCT(
        'activity', 'go no go', 
        'wait for previous batch run', true
    ) PARAMETERS;

-----------------------------------------

-- JOB_D9318_GORWCA_D_CLOSE_BATCH   
DELETE FROM D_DWH.ETL_FW.BATCH_JOB WHERE BATCH_NAME = 'D9318_GORWCA_D' and JOB_NAME = 'JOB_D9318_GORWCA_D_CLOSE_BATCH';    

INSERT INTO D_DWH.ETL_FW.BATCH_JOB(JOB_NAME, SRC_SYS, BATCH_NAME, JOB_TYPE, PARAMETERS)
SELECT  'JOB_D9318_GORWCA_D_CLOSE_BATCH' JOB_NAME, 
    NULL SRC_SYS,
    'D9318_GORWCA_D' BATCH_NAME,
    'BATCH_MAINTENANCE' JOB_TYPE,
    OBJECT_CONSTRUCT(
        'activity', 'close batch', 
        'mark batch as done', true
    ) PARAMETERS;

----------------------------------------
--JOB_TXF_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_T01_D
DELETE FROM D_DWH.ETL_FW.BATCH_JOB WHERE BATCH_NAME = 'D9318_GORWCA_D' and JOB_NAME = 'JOB_TXF_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_T01_D';

INSERT INTO D_DWH.ETL_FW.BATCH_JOB(JOB_NAME, SRC_SYS, BATCH_NAME, JOB_TYPE, PARAMETERS) 
SELECT 'JOB_TXF_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_T01_D' 		AS JOB_NAME, --T## -- stands for how many tables the report uses 
NULL 														AS SRC_SYS, 
'D9318_GORWCA_D' 										    AS BATCH_NAME, -- DSF stands for downstream 
'TRANSFORMATION' 											AS JOB_TYPE,
	OBJECT_CONSTRUCT
	(
		'load_pattern', 'km_dsf_upsert',	             
        'source','DB_CONSUMER_BANKING.WGORWCA.XV_TXF_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_T01_D',
		'target','DB_CONSUMER_BANKING.TGORWCA.T_GOREWARDS_CREDIT_ACCRUAL',
		'key_columns', 'ACCT_NUM,BUSINESSDATE_PT',
		'data_columns', 'RETAILERID,STOREID,POSID,CASHIERID,TICKETTOTAL,BUSINESSDATE,STARTDATETIME,TRANSID,CARDID,SERVERDATE,EARNVALUE,FIRSTNAME,LASTNAME,BIRTHDATE,EMAILADDRESS,MOBILENUMBER,CUSTOMERTIER,REWARDS_ACCT_NUM,TSYS_CARDID,GENERATEDATETIME,CYCLE_DATE'
) PARAMETERS;

--------------------------------------------

-- JOB_EXP_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_T01_D
DELETE FROM D_DWH.ETL_FW.BATCH_JOB WHERE JOB_NAME = 'JOB_EXP_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_T01_D';
 
INSERT INTO D_DWH.ETL_FW.BATCH_JOB(BATCH_NAME, JOB_NAME, JOB_TYPE, PARAMETERS)
SELECT 
'D9318_GORWCA_D' BATCH_NAME,  
'JOB_EXP_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_T01_D' JOB_NAME, 
'TRANSFORMATION' JOB_TYPE,
OBJECT_CONSTRUCT
  (
	'source_view', 'DB_CONSUMER_BANKING.WGORWCA.XV_EXP_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_T01_D',
	'file_name', 'SF_UBP-Credit_PointsEarning_%Y%m%d%H%M%S', 
    'file_type', 'CSV',
    'load_pattern', 'km_external_fs_export',
    'processing_type', 'sftp',
    'secret_keys', 'sftp_sf_davi_integration',
    
	'file_path', '/opt/GoRewards/UAT/CLM_Accrual/Credit_test', --Production Path
	'disable_audit_column', true,
    'thea_default_subdir', false,
    'thea_biz_date_dir_enabled', false,
    'type_options',
                {
                    'compression' : 'NONE',
                    'parse_header' : 'TRUE',
                    'field_delimiter' : ','
                }
  ) PARAMETERS;
