-- PARTITION KEY
CREATE OR REPLACE VIEW DB_CONSUMER_BANKING.WGORWCA.XV_PARTITION_KEY_BGORWCA_D(
	BATCH_NAME,
	LOW_DT,
	HIGH_DT
) as (
SELECT BATCH_NAME,
   LAST_BIZ_DATE + 1 AS LOW_DT,
   BIZ_DATE AS HIGH_DT
FROM D_DWH.ETL_FW.D9318_GORWCA_D_BATCH);




CREATE OR REPLACE TABLE DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY (
	BATCH_NAME VARCHAR(16777216),
	LOW_DT DATE,
	HIGH_DT DATE,
	AS_OF_DATE DATE,
	JOB_RUN_ID NUMBER(38,0),
	UPDATE_TS TIMESTAMP_NTZ(9)
);
