SELECT job_name,batch_name,job_type, PARAMETERS:snapshot_type FROM D_DWH.ETL_FW.BATCH_JOB WHERE JOB_NAME LIKE '%TCTDBS_CCUSTOMERS%';

---------------------------

create or replace view DB_CONSUMER_BANKING.BGORWCA_D.V_TCTDBS_CCUSTOMERS
 as    
SELECT *
FROM D_DWH_SRC.EOD_TSYS.T_TCTDBS_CCUSTOMERS_HIST AS CUS
CROSS JOIN (SELECT HIGH_DT FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY
WHERE BATCH_NAME ='D9318_GORWCA_D')BD 
WHERE 1=1 and CUS.AS_OF_DATE=BD.HIGH_DT;

----------------

create or replace view DB_CONSUMER_BANKING.BGORWCA_D.V_TCTDBS_PEOPLE
AS
select * from D_DWH_SRC.EOD_TSYS.T_TCTDBS_PEOPLE_HIST A
CROSS JOIN (SELECT HIGH_DT FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY WHERE BATCH_NAME ='D9318_GORWCA_D')BD 
WHERE 1=1 and A.AS_OF_DATE=BD.HIGH_DT;

-------------------


create or replace view DB_CONSUMER_BANKING.BGORWCA_D.V_TCTDBS_CADDRESSES
AS
Select * from D_DWH_SRC.EOD_TSYS.T_TCTDBS_CADDRESSES_HIST A
CROSS JOIN (SELECT HIGH_DT FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY WHERE BATCH_NAME ='D9318_GORWCA_D')BD 
WHERE 1=1 and A.AS_OF_DATE=BD.HIGH_DT;
-------------------

create or replace view DB_CONSUMER_BANKING.BGORWCA_D.V_TCTDBS_CADDRESSLINKS
AS
Select * from D_DWH_SRC.EOD_TSYS.T_TCTDBS_CADDRESSLINKS_HIST A
CROSS JOIN (SELECT HIGH_DT FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY WHERE BATCH_NAME ='D9318_GORWCA_D')BD 
WHERE 1=1 and A.AS_OF_DATE=BD.HIGH_DT;

--------------------------

create or replace view DB_CONSUMER_BANKING.BGORWCA_D.V_TCTDBS_CACCOUNTS
AS
Select * from D_DWH_SRC.EOD_TSYS.T_TCTDBS_CACCOUNTS_HIST A
CROSS JOIN (SELECT HIGH_DT FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY WHERE BATCH_NAME ='D9318_GORWCA_D')BD 
WHERE 1=1 and A.AS_OF_DATE=BD.HIGH_DT;

------------------------------------

create or replace view DB_CONSUMER_BANKING.BGORWCA_D.V_TCTDBS_PRODUCTS
AS
Select * from D_DWH_SRC.EOD_TSYS.T_TCTDBS_PRODUCTS_HIST A
CROSS JOIN (SELECT HIGH_DT FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY WHERE BATCH_NAME ='D9318_GORWCA_D')BD 
WHERE 1=1 and A.AS_OF_DATE=BD.HIGH_DT;

----------------------------

create or replace view DB_CONSUMER_BANKING.BGORWCA_D.V_TCTDBS_CEXTENSION
AS
Select * from D_DWH_SRC.EOD_TSYS.T_TCTDBS_CEXTENSION_HIST A
CROSS JOIN (SELECT HIGH_DT FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY WHERE BATCH_NAME ='D9318_GORWCA_D')BD 
WHERE 1=1 and A.AS_OF_DATE=BD.HIGH_DT;


-----------------------------


CREATE OR REPLACE VIEW DB_CONSUMER_BANKING.BGORWCA_D.V_TCTDBS_CSTATEMENTS_HIST AS
SELECT A.*
FROM (
    -- First part of the union query
    SELECT CSTMT.*
    FROM D_DWH_SRC.EOD_TSYS.T_TCTDBS_CSTATEMENTS_HIST CSTMT
    INNER JOIN D_DWH.ETL_FW.JOB_RUN JR ON JR.JOB_RUN_ID = CSTMT.JOB_RUN_ID
    CROSS JOIN D_DWH.ETL_FW.D9318_GORWCA_D_BATCH EB
    WHERE EB.BIZ_DATE BETWEEN CSTMT.BIZ_DATE AND JR.BIZ_DATE - 1
    AND CSTMT.SOFT_DELETE_FLAG IS NOT NULL
 
    UNION
 
    -- Second part of the union query
    SELECT CSTMT.*
    FROM D_DWH_SRC.EOD_TSYS.T_TCTDBS_CSTATEMENTS_HIST CSTMT
    CROSS JOIN D_DWH.ETL_FW.D9318_GORWCA_D_BATCH EB
    WHERE CSTMT.BIZ_DATE <= EB.BIZ_DATE
    AND CSTMT.SOFT_DELETE_FLAG IS NULL
) A
CROSS JOIN (
    SELECT HIGH_DT AS BIZ_DATE
    FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY
    WHERE BATCH_NAME = 'D9318_GORWCA_D'
) BD
WHERE 1=1 AND  A.BIZ_DATE <= BD.BIZ_DATE;

-------------------------------


create or replace view DB_CONSUMER_BANKING.BGORWCA_D.V_ODS_LKP_GOREWARDS_PRODUCTS
  as  
SELECT *
FROM D_DWH_SRC.EOD_FLAT_FILES.T_ODS_LKP_GOREWARDS_PRODUCTS_HIST GRML
CROSS JOIN (SELECT HIGH_DT FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY WHERE BATCH_NAME ='D9318_GORWCA_D')BD
WHERE 1=1 and grml.AS_OF_DATE=BD.HIGH_DT

-------------------------------

create or replace view DB_CONSUMER_BANKING.BGORWCA_D.V_GOREWARDS_MASTER_LIST
  as    
SELECT *
FROM D_DWH_SRC.EOD_EXADATA.T_DATALAKE_IHMI_GOREWARDS_MASTER_LIST_HIST GRML;


