
CREATE OR REPLACE VIEW DB_CONSUMER_BANKING.WGORWCA.XV_RCN_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_W01_D
AS
WITH
------------------------------
-- CLOUDERA
------------------------------
CTE_SRC_CLOUDERA_DATA AS
(
    SELECT RETAILERID, STOREID, POSID, CASHIERID, TICKETTOTAL, BUSINESSDATE, STARTDATETIME, TRANSID, CARDID,  EARNVALUE, FIRSTNAME, LASTNAME, BIRTHDATE,EMAILADDRESS, MOBILENUMBER, CUSTOMERTIER, REWARDS_ACCT_NUM, ACCT_NUM, TSYS_CARDID, GENERATEDATETIME, CYCLEDATE, BUSINESSDATE_PT
    FROM DB_CDH_MIG.CDH_RECON.ODS_GOREWARDS_CREDIT_ACCRUAL 
    WHERE 1=1 
	AND BUSINESSDATE_PT = (SELECT TO_CHAR(HIGH_DT,'YYYYMMDD') FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY) 
    GROUP BY ALL
) ,
-----------------------
--CTE_TGT_SNOWFLAKE
-----------------------
CTE_TGT_SNOWFLAKE_DATA AS
(
    SELECT RETAILERID, STOREID, POSID, CASHIERID, TICKETTOTAL, BUSINESSDATE, STARTDATETIME, TRANSID, CARDID,  EARNVALUE, FIRSTNAME, LASTNAME, BIRTHDATE, EMAILADDRESS, MOBILENUMBER, CUSTOMERTIER, REWARDS_ACCT_NUM, ACCT_NUM, TSYS_CARDID, GENERATEDATETIME, CYCLE_DATE,BUSINESSDATE_PT
    FROM DB_CONSUMER_BANKING.TGORWCA.T_GOREWARDS_CREDIT_ACCRUAL
    WHERE 1=1
	AND BUSINESSDATE_PT = (SELECT TO_CHAR(HIGH_DT,'YYYYMMDD') FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY)
    AND AS_OF_DATE =  
    (SELECT HIGH_DT FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY) 
	GROUP BY ALL
)
-----------------------
--MAIN SELECT
-----------------------
SELECT
		SRC.RETAILERID 			AS SRC_RETAILERID, 
		TGT.RETAILERID 			AS TGT_RETAILERID,
		SRC.STOREID 			AS SRC_STOREID, 
		TGT.STOREID 			AS TGT_STOREID,
		SRC.POSID 				AS SRC_POSID, 
		TGT.POSID 				AS TGT_POSID,
		SRC.CASHIERID 			AS SRC_CASHIERID, 
		TGT.CASHIERID 			AS TGT_CASHIERID,
		SRC.TICKETTOTAL 		AS SRC_TICKETTOTAL, 
		TGT.TICKETTOTAL 		AS TGT_TICKETTOTAL,
		SRC.BUSINESSDATE 		AS SRC_BUSINESSDATE, 
		TGT.BUSINESSDATE 		AS TGT_BUSINESSDATE,
		SRC.STARTDATETIME 		AS SRC_STARTDATETIME, 
		TGT.STARTDATETIME 		AS TGT_STARTDATETIME,
		SRC.TRANSID 			AS SRC_TRANSID, 
		TGT.TRANSID 			AS TGT_TRANSID,
		SRC.CARDID 				AS SRC_CARDID, 
		TGT.CARDID 				AS TGT_CARDID,
		SRC.EARNVALUE 			AS SRC_EARNVALUE, 
		TGT.EARNVALUE 			AS TGT_EARNVALUE,
		SRC.FIRSTNAME 			AS SRC_FIRSTNAME, 
		TGT.FIRSTNAME 			AS TGT_FIRSTNAME,
		SRC.LASTNAME 			AS SRC_LASTNAME, 
		TGT.LASTNAME 			AS TGT_LASTNAME,
		SRC.BIRTHDATE 			AS SRC_BIRTHDATE, 
		TGT.BIRTHDATE 			AS TGT_BIRTHDATE,
		SRC.EMAILADDRESS 		AS SRC_EMAILADDRESS, 
		TGT.EMAILADDRESS 		AS TGT_EMAILADDRESS,
		SRC.MOBILENUMBER 		AS SRC_MOBILENUMBER, 
		TGT.MOBILENUMBER 		AS TGT_MOBILENUMBER,
		SRC.CUSTOMERTIER 		AS SRC_CUSTOMERTIER, 
		TGT.CUSTOMERTIER 		AS TGT_CUSTOMERTIER,
		SRC.REWARDS_ACCT_NUM 	AS SRC_REWARDS_ACCT_NUM, 
		TGT.REWARDS_ACCT_NUM 	AS TGT_REWARDS_ACCT_NUM,
		SRC.ACCT_NUM 			AS SRC_ACCT_NUM, 
		TGT.ACCT_NUM 			AS TGT_ACCT_NUM,
		SRC.TSYS_CARDID 		AS SRC_TSYS_CARDID, 
		TGT.TSYS_CARDID 		AS TGT_TSYS_CARDID,
		SRC.GENERATEDATETIME 	AS SRC_GENERATEDATETIME, 
		TGT.GENERATEDATETIME 	AS TGT_GENERATEDATETIME,
		SRC.CYCLEDATE 			AS SRC_CYCLE_DATE, 
		TGT.CYCLE_DATE 			AS TGT_CYCLE_DATE,
		SRC.BUSINESSDATE_PT 	AS SRC_BUSINESSDATE_PT, 
		TGT.BUSINESSDATE_PT 	AS TGT_BUSINESSDATE_PT,

	ROW_NUMBER() OVER (PARTITION BY TGT.TRANSID ORDER BY TGT.TRANSID, TGT.GENERATEDATETIME ASC)	AS 	RN,
------------------------------------------
-- COLUMNS STATUS
------------------------------------------
    CASE WHEN NVL(TRIM(SRC.RETAILERID), '') = NVL(TRIM(TGT.RETAILERID), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS RETAILER_ID_STATUS,
	CASE WHEN NVL(TRIM(SRC.STOREID), '') = NVL(TRIM(TGT.STOREID), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS STORE_ID_STATUS,
	CASE WHEN NVL(TRIM(SRC.POSID), '') = NVL(TRIM(TGT.POSID), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS POS_ID_STATUS,
	CASE WHEN NVL(TRIM(SRC.CASHIERID), '') = NVL(TRIM(TGT.CASHIERID), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS CASHIER_ID_STATUS,
	CASE WHEN NVL(TRIM(SRC.TICKETTOTAL), '') = NVL(TRIM(TGT.TICKETTOTAL), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS TICKET_TOTAL_STATUS,
	CASE WHEN NVL(TRIM(SRC.BUSINESSDATE), '') = NVL(TRIM(TGT.BUSINESSDATE), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS BUSINESS_DATE_STATUS,
	CASE WHEN NVL(TRIM(SRC.STARTDATETIME), '') = NVL(TRIM(TGT.STARTDATETIME), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS START_DATE_TIME_STATUS,
	CASE WHEN NVL(TRIM(SRC.TRANSID), '') = NVL(TRIM(TGT.TRANSID), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS TRANS_ID_STATUS,
	CASE WHEN NVL(TRIM(SRC.CARDID), '') = NVL(TRIM(TGT.CARDID), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS CARD_ID_STATUS,
	CASE WHEN NVL(TRIM(SRC.EARNVALUE), '') = NVL(TRIM(TGT.EARNVALUE), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS EARN_VALUE_STATUS,
	CASE WHEN NVL(TRIM(SRC.FIRSTNAME), '') = NVL(TRIM(TGT.FIRSTNAME), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS FIRST_NAME_STATUS,
	CASE WHEN NVL(TRIM(SRC.LASTNAME), '') = NVL(TRIM(TGT.LASTNAME), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS LAST_NAME_STATUS,
	CASE WHEN NVL(TRIM(SRC.BIRTHDATE), '') = NVL(TRIM(TGT.BIRTHDATE), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS BIRTH_DATE_STATUS,
	CASE WHEN NVL(TRIM(SRC.EMAILADDRESS), '') = NVL(TRIM(TGT.EMAILADDRESS), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS EMAIL_ADDRESS_STATUS,
	CASE WHEN NVL(TRIM(SRC.MOBILENUMBER), '') = NVL(TRIM(TGT.MOBILENUMBER), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS MOBILE_NUMBER_STATUS,
	CASE WHEN NVL(TRIM(SRC.CUSTOMERTIER), '') = NVL(TRIM(TGT.CUSTOMERTIER), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS CUSTOMER_TIER_STATUS,
	CASE WHEN NVL(TRIM(SRC.REWARDS_ACCT_NUM), '') = NVL(TRIM(TGT.REWARDS_ACCT_NUM), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS REWARDS_ACCT_NUM_STATUS,
	CASE WHEN NVL(TRIM(SRC.ACCT_NUM), '') = NVL(TRIM(TGT.ACCT_NUM), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS ACCT_NUM_STATUS,
	CASE WHEN NVL(TRIM(SRC.TSYS_CARDID), '') = NVL(TRIM(TGT.TSYS_CARDID), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS TSYS_CARD_ID_STATUS,
	CASE WHEN NVL(TRIM(SRC.GENERATEDATETIME), '') = NVL(TRIM(TGT.GENERATEDATETIME), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS GENERATED_DATE_TIME_STATUS,
	CASE WHEN NVL(TRIM(SRC.CYCLEDATE), '') = NVL(TRIM(TGT.CYCLE_DATE), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS CYCLE_DATE_STATUS,
	CASE WHEN NVL(TRIM(SRC.BUSINESSDATE_PT), '') = NVL(TRIM(TGT.BUSINESSDATE_PT), '') THEN 'MATCHED' ELSE 'NOT_MATCHED' END AS BUSINESS_DATE_PT_STATUS

------------------------------------------
-- ALL COLUMNS STATUS
------------------------------------------
    , CASE WHEN
    RETAILER_ID_STATUS = 'MATCHED' 
    AND STORE_ID_STATUS = 'MATCHED' 
    AND POS_ID_STATUS = 'MATCHED' 
    AND CASHIER_ID_STATUS = 'MATCHED' 
    AND TICKET_TOTAL_STATUS = 'MATCHED' 
    AND BUSINESS_DATE_STATUS = 'MATCHED' 
    AND START_DATE_TIME_STATUS = 'MATCHED' 
    AND TRANS_ID_STATUS = 'MATCHED' 
    AND CARD_ID_STATUS = 'MATCHED' 
    AND EARN_VALUE_STATUS = 'MATCHED' 
    AND FIRST_NAME_STATUS = 'MATCHED' 
    AND LAST_NAME_STATUS = 'MATCHED' 
    AND BIRTH_DATE_STATUS = 'MATCHED' 
    AND EMAIL_ADDRESS_STATUS = 'MATCHED' 
    AND MOBILE_NUMBER_STATUS = 'MATCHED' 
    AND CUSTOMER_TIER_STATUS = 'MATCHED' 
    AND REWARDS_ACCT_NUM_STATUS = 'MATCHED' 
    AND ACCT_NUM_STATUS = 'MATCHED' 
    AND TSYS_CARD_ID_STATUS = 'MATCHED' 
    AND GENERATED_DATE_TIME_STATUS = 'MATCHED' 
    AND CYCLE_DATE_STATUS = 'MATCHED' 
    AND BUSINESS_DATE_PT_STATUS = 'MATCHED' 
THEN 'MATCHED' 
ELSE 'NOT_MATCHED' 
END AS ALL_COLUMNS_STATUS
FROM
    CTE_SRC_CLOUDERA_DATA SRC
FULL JOIN CTE_TGT_SNOWFLAKE_DATA TGT 
ON SRC.TRANSID = TGT.TRANSID
WHERE 1=1
ORDER BY RN ASC;