DELETE FROM D_DWH.ETL_FW.BATCH_JOB WHERE BATCH_NAME = 'D9318_GORWCA_D' and JOB_NAME = 'JOB_RCN_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_W01_D';

INSERT INTO D_DWH.ETL_FW.BATCH_JOB(JOB_NAME, SRC_SYS, BATCH_NAME, JOB_TYPE, PARAMETERS) 
SELECT 'JOB_RCN_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_W01_D'				AS JOB_NAME, --T0X -- stands for how many tables the report uses 
NULL 											AS SRC_SYS, 
'D9318_GORWCA_D' 								AS BATCH_NAME, -- DSF stands for downstream 
'TRANSFORMATION' 								AS JOB_TYPE,
	OBJECT_CONSTRUCT
	(
		'data_columns', 'SRC_RETAILERID, TGT_RETAILERID, SRC_STOREID, TGT_STOREID, SRC_POSID, TGT_POSID, SRC_CASHIERID, TGT_CASHIERID, SRC_TICKETTOTAL, 
TGT_TICKETTOTAL, SRC_BUSINESSDATE, TGT_BUSINESSDATE, SRC_STARTDATETIME, TGT_STARTDATETIME, SRC_TRANSID, TGT_TRANSID, SRC_CARDID, 
TGT_CARDID,  SRC_EARNVALUE, TGT_EARNVALUE, SRC_FIRSTNAME, TGT_FIRSTNAME, SRC_LASTNAME, TGT_LASTNAME, 
SRC_BIRTHDATE, TGT_BIRTHDATE, SRC_EMAILADDRESS, TGT_EMAILADDRESS, SRC_MOBILENUMBER, TGT_MOBILENUMBER, SRC_CUSTOMERTIER, 
TGT_CUSTOMERTIER, SRC_REWARDS_ACCT_NUM, TGT_REWARDS_ACCT_NUM,  SRC_TSYS_CARDID, TGT_TSYS_CARDID, SRC_GENERATEDATETIME, 
TGT_GENERATEDATETIME, SRC_CYCLE_DATE, TGT_CYCLE_DATE, RETAILER_ID_STATUS, STORE_ID_STATUS, POS_ID_STATUS, CASHIER_ID_STATUS, 
TICKET_TOTAL_STATUS, BUSINESS_DATE_STATUS, START_DATE_TIME_STATUS, TRANS_ID_STATUS, CARD_ID_STATUS, 
EARN_VALUE_STATUS, FIRST_NAME_STATUS, LAST_NAME_STATUS, BIRTH_DATE_STATUS, EMAIL_ADDRESS_STATUS, MOBILE_NUMBER_STATUS, 
CUSTOMER_TIER_STATUS, REWARDS_ACCT_NUM_STATUS, ACCT_NUM_STATUS, TSYS_CARD_ID_STATUS, GENERATED_DATE_TIME_STATUS, 
CYCLE_DATE_STATUS, BUSINESS_DATE_PT_STATUS, ALL_COLUMNS_STATUS
',
		'key_columns', 'RN,SRC_ACCT_NUM, TGT_ACCT_NUM,SRC_BUSINESSDATE_PT, TGT_BUSINESSDATE_PT',
		'load_pattern', 'km_dsf_insert',
		'truncate_table_before_loading', false,
		'source', 'DB_CONSUMER_BANKING.WGORWCA.XV_RCN_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_W01_D',
		'target', 'DB_CONSUMER_BANKING.WGORWCA.T_RCN_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_W01_D'
	) PARAMETERS;