create or replace view DB_CONSUMER_BANKING.WGORWCA.XV_EXP_CDH345_GOREWARDS_CREDIT_ACCRUAL_D9318_T01_D(
	RETAILERID,
	STOREID,
	POSID,
	CASHIERID,
	TICKETTOTAL,
	BUSINESSDATE,
	STARTDATETIME,
	TRANSID,
	CARDID,
	SERVERDATE,
	EARNVALUE,
	FIRSTNAME,
	LASTNAME,
	BIRTHDATE,
	EMAILADDRESS,
	MOBILENUMBER,
	CUSTOMERTIER
) as
Select RetailerId,StoreID,PosID,CashierID,TicketTotal, BusinessDate,StartDateTime,TransID,CardID,ServerDate,EarnValue,FirstName,LastName,BirthDate,EmailAddress,MobileNumber,CustomerTier 
FROM DB_CONSUMER_BANKING.TGORWCA.T_GOREWARDS_CREDIT_ACCRUAL 
WHERE 
businessdate_pt = (SELECT TO_CHAR(HIGH_DT,'YYYYMMDD') FROM DB_CONSUMER_BANKING.BGORWCA_D.PARTITION_KEY) 
and 
cardid is not null and regexp_replace(cardid,'[^0-9]','') <> '';