name: Schemachange Deploy

on:
  push:
    branches:
      - cpe_int

jobs:
  schemachange:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install schemachange
        run: |
          python -m pip install --upgrade pip
          pip install schemachange

      - name: Install SnowSQL
        run: |
          curl -L https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.27-linux_x86_64.bash \
            -o snowsql_install.bash
          bash snowsql_install.bash -y
          echo "$HOME/.snowsql/bin" >> $GITHUB_PATH

      - name: Write Snowflake private key
        run: |
          mkdir -p ~/.ssh
          echo "$SNOWFLAKE_PRIVATE_KEY" > ~/.ssh/snowflake_key.pem
          chmod 600 ~/.ssh/snowflake_key.pem
        env:
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

      - name: Test Snowflake connection
        run: |
          snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
                  -u ${{ secrets.SNOWFLAKE_USER }} \
                  -w ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
                  -d ${{ secrets.SNOWFLAKE_DATABASE }} \
                  -s ${{ secrets.SNOWFLAKE_SCHEMA }} \
                  --private-key-path ~/.ssh/snowflake_key.pem \
                  -q "SELECT CURRENT_USER(), CURRENT_ACCOUNT(), CURRENT_VERSION();"

      - name: Run schemachange migrations
        run: |
          schemachange -f migrations \
            -a "${{ secrets.SNOWFLAKE_ACCOUNT }}" \
            -u "${{ secrets.SNOWFLAKE_USER }}" \
            --private-key-path ~/.ssh/snowflake_key.pem \
            -w "${{ secrets.SNOWFLAKE_WAREHOUSE }}" \
            -d "${{ secrets.SNOWFLAKE_DATABASE }}" \
            -s "${{ secrets.SNOWFLAKE_SCHEMA }}" \
            -t SCHEMACHANGE_CHANGELOG
